import { PrismaClient, Prisma } from "@prisma/client";

export {
  PrismaClient,
  Prisma,

  // Core Enums from schema.prisma (Verified present in generated client)
  AiActionStatus,
  ApiKeyStatus,
  AppRole,
  ApprovalStatus,
  BillingProvider,
  CampaignChannel,
  CampaignSendStatus,
  CampaignStatus,
  CampaignType,
  Channel,
  ChecklistCategory,
  ChecklistStatus,
  ConsentChannel,
  ConsentEventType,
  ConsentSource,
  CouponStatus,
  DLQStatus,
  DataRequestStatus,
  DataRequestType,
  DeviceStatus,
  DeviceType,
  Direction,
  DiscountAppliesTo,
  DiscountType,
  DisputeEvidenceType,
  DisputeProvider,
  DisputeStatus,
  EnforcementActionType,
  EnforcementScope,
  EvidenceFileType,
  EvidenceScope,
  FlagSeverity,
  FulfillmentStatus,
  IdempotencyStatus,
  JobRunStatus,
  KycStatus,
  LegalKey,
  ListingStatus,
  MessageStatus,
  MessageType,
  MetricPeriod,
  MigrationStatus,
  OnboardingStatus,
  OrderStatus,
  OutboxEventStatus,
  PaymentStatus,
  PolicyStatus,
  PolicyType,
  ReportEntityType,
  ReportReason,
  ReportStatus,
  RestockAction,
  ReturnCondition,
  ReturnMethod,
  ReturnReason,
  ReturnResolution,
  ReturnStatus,
  ReviewStatus,
  RiskScope,
  RiskSeverity,
  RiskStatus,
  SubscriptionPlan,
  SubscriptionStatus,
  SupportCaseCategory,
  SupportCaseStatus,
  ThemeStatus,
  VirtualAccountStatus,
  WebhookDeliveryStatus,
  WebhookEndpointStatus,
  ExportStatus,
  DataDeletionStatus,
  DeletionStatus,
} from "@prisma/client";

// Types are safe to wildcard export as they don't trigger Turbopack re-export warnings
export type * from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
