
import { prisma } from '@vayva/db';

export class IncidentManager {

    static async triggerIncident(checkId: string, checkName: string) {
        // 1. Check for existing active incident linked to this check
        const existing = await prisma.incidentLink.findFirst({
            where: {
                uptimeCheckId: checkId,
                incident: {
                    status: { in: ['investigating', 'identified', 'monitoring'] }
                }
            }
        });

        if (existing) return; // Already tracking

        // 2. Create Incident
        const incident = await prisma.statusIncident.create({
            data: {
                title: `Service disruption: ${checkName}`,
                status: 'investigating',
                impact: 'major', // Default to major for V1 automation
                autoGenerated: true,
                createdBy: 'system',
                updates: {
                    create: {
                        message: `Automated alert: Elevated failure rate detected on ${checkName}.`,
                        authorType: 'system'
                    }
                },
                links: {
                    create: {
                        uptimeCheckId: checkId
                    }
                }
            }
        });

        console.log(`[INCIDENT] Created ${incident.id} for ${checkName}`);
        // Notifications to Email/Slack would go here
    }

    static async resolveIncident(incidentId: string, reason: string) {
        await prisma.$transaction([
            prisma.statusIncident.update({
                where: { id: incidentId },
                data: {
                    status: 'resolved',
                    resolvedAt: new Date()
                }
            }),
            prisma.statusIncidentUpdate.create({
                data: {
                    incidentId,
                    message: `Resolved: ${reason}`,
                    authorType: 'admin' // Or system
                }
            })
        ]);
    }
}
